# Generated by Django 5.0.3 on 2024-03-26 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level_range_low', models.IntegerField()),
                ('level_range_high', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('keywords', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='are_editor.area')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnum', models.IntegerField()),
                ('keywords', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
                ('description', models.TextField()),
                ('act_flags', models.IntegerField()),
                ('affected_flags', models.IntegerField()),
                ('alignment', models.IntegerField()),
                ('level', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='are_editor.area')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnum', models.IntegerField()),
                ('keywords', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
                ('action_description', models.TextField(blank=True)),
                ('item_type', models.IntegerField()),
                ('extra_flags', models.IntegerField()),
                ('wear_flags', models.IntegerField()),
                ('value_0', models.IntegerField()),
                ('value_1', models.IntegerField()),
                ('value_2', models.IntegerField()),
                ('value_3', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='are_editor.area')),
            ],
        ),
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=1)),
                ('command_type', models.CharField(choices=[('M', 'Mobile'), ('O', 'Object'), ('P', 'Put Object in Object'), ('G', 'Give Object to Mobile'), ('E', 'Equip Object to Mobile'), ('D', 'Set State of Door'), ('R', 'Randomize Room Exits')], max_length=1)),
                ('mob_vnum', models.IntegerField(blank=True, null=True)),
                ('obj_vnum', models.IntegerField(blank=True, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('room_vnum', models.IntegerField(blank=True, null=True)),
                ('door_number', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='are_editor.area')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnum', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('room_flags', models.IntegerField()),
                ('sector_type', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='are_editor.area')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keeper', models.IntegerField()),
                ('trade_0', models.IntegerField()),
                ('trade_1', models.IntegerField()),
                ('trade_2', models.IntegerField()),
                ('trade_3', models.IntegerField()),
                ('trade_4', models.IntegerField()),
                ('profit_buy', models.IntegerField()),
                ('profit_sell', models.IntegerField()),
                ('open_hour', models.IntegerField()),
                ('close_hour', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='are_editor.area')),
            ],
        ),
        migrations.CreateModel(
            name='ShopInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='are_editor.object')),
                ('shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='are_editor.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_vnum', models.IntegerField()),
                ('spec_fun', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='are_editor.area')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='are_editor.special')),
            ],
        ),
    ]
